#!/bin/bash

ip="51.81.26.21"
ipVpn="10.8.0.2"
ipBjshare="104.18.52.41"
path="/root/bin/firewallArquivos"
ipsBlock="$path/ipsBlock"
ipsConfiaveis="$path/ipsConfiaveis"
ipsNtp="$path/ipsNtp"

# Limpando
iptables -F
iptables -X
iptables -t nat -F
iptables -t nat -X

# Loopback
iptables -A INPUT	-i lo -s 127.0.0.1 -j ACCEPT
iptables -A OUTPUT	-o lo -d 127.0.0.1 -j ACCEPT

# Reinicia o DOCKER para aplicar suas regras de Firewall
service docker restart

# Bloqueia tudo, pois a regra do DOCKER vem acima
iptables -I FORWARD -j DROP

# Bloqueando IPs
# Liberanndo os IPs confiáveis
if [[ -f $ipsBlock ]]; then
	for x in $(cat $ipsBlock | uniq | sort -n); do
		iptables -A INPUT	-s $x -j DROP
		iptables -A OUTPUT	-d $x -j DROP
		iptables -I FORWARD -s $x -j DROP
		iptables -I FORWARD -d $x -j DROP
	done
fi

# Pacotes estabelecidos e relacionados
iptables -A INPUT	-m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A OUTPUT	-m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -I FORWARD	-m state --state ESTABLISHED,RELATED -j ACCEPT

# PING
iptables -A INPUT	-p icmp --icmp-type echo-request -m limit --limit 1/s -j ACCEPT
iptables -A OUTPUT	-p icmp --icmp-type echo-request -m limit --limit 1/s -j ACCEPT
iptables -I FORWARD	-p icmp --icmp-type echo-request -m limit --limit 1/s -j ACCEPT

# SSH
iptables -A INPUT -p tcp --dport 22922 -d $ip -j ACCEPT

# Navegação
iptables -A OUTPUT 	-p tcp --dport 80	-j ACCEPT
iptables -A OUTPUT 	-p tcp --dport 443	-j ACCEPT
iptables -I FORWARD -p tcp --dport 80	-j ACCEPT
iptables -I FORWARD -p tcp --dport 443	-j ACCEPT

# DNS
iptables -A INPUT	-p tcp --dport 53 -d $ip -j ACCEPT
iptables -A INPUT	-p udp --dport 53 -d $ip -j ACCEPT
iptables -A OUTPUT	-p tcp --dport 53 -s $ip -j ACCEPT
iptables -A OUTPUT	-p udp --dport 53 -s $ip -j ACCEPT
iptables -I FORWARD -p tcp --dport 53 -j ACCEPT
iptables -I FORWARD -p udp --dport 53 -j ACCEPT
iptables -I FORWARD -p tcp --sport 53 -j ACCEPT
iptables -I FORWARD -p udp --sport 53 -j ACCEPT

# SMTP
iptables -I FORWARD	-p tcp --sport 25 -j ACCEPT
iptables -I FORWARD	-p tcp --dport 25 -j ACCEPT

# Descarta pacotes reincidentes/persistentes
iptables -A INPUT -m recent --update --name SUSPEITO -m limit --limit 10/min --limit-burst 3 -j LOG --log-level 6 --log-prefix "FIREWALL: suspeito: "
iptables -A INPUT -m recent --update --hitcount 10 --name SUSPEITO --seconds 86400 -j DROP
iptables -A INPUT -m recent --update --hitcount 5  --name SUSPEITO --seconds 3600  -j DROP
iptables -I FORWARD -m recent --update --hitcount 10 --name SUSPEITO --seconds 86400 -j DROP
iptables -I FORWARD -m recent --update --hitcount 5  --name SUSPEITO --seconds 3600  -j DROP


# Descarta pacotes inválidos
iptables -A INPUT	-m state --state INVALID -j DROP
iptables -I FORWARD -m state --state INVALID -j DROP

# Aceitando as conexões do DOCKER para o DOCKER
iptables -A INPUT -s 172.17.0.0/16 -d 172.17.0.0/16 -j ACCEPT
iptables -A OUTPUT -s 172.17.0.0/16 -d 172.17.0.0/16 -j ACCEPT
#******************#
# Área com so FORs #
#******************#
# Liberanndo os IPs confiáveis
if [[ -f $ipsConfiaveis ]]; then
	for x in $(cat $ipsConfiaveis | uniq | sort -n); do
		iptables -I FORWARD -p tcp --dport 465 -s $x -j ACCEPT
		iptables -I FORWARD -p tcp --dport 993 -s $x -j ACCEPT
		iptables -I FORWARD -p tcp --dport 995 -s $x -j ACCEPT
	done
fi

# Liberando NTP
if [[ -f $ipsNtp ]]; then
	for x in $(cat $ipsNtp | uniq | sort -n); do
		iptables -A OUTPUT -p udp --dport 123 -s $ip -j ACCEPT
	done
fi


#*********************************#
# Não colocar regras abaixo daqui #
#*********************************#
# Dropgando tudo que é ipv6
ip6tables -A INPUT	-j DROP
ip6tables -A OUTPUT	-j DROP
ip6tables -A FORWARD	-j DROP

# Logando o que restou
iptables -A INPUT	-j LOG --log-level 6 --log-prefix "FIREWALL: drop input: "
iptables -A OUTPUT	-j LOG --log-level 6 --log-prefix "FIREWALL: drop output: "
iptables -A FORWARD	-j LOG --log-level 6 --log-prefix "FIREWALL: drop forward: "

# Droptando o restante
iptables -A INPUT		-j DROP
iptables -A OUTPUT 		-j DROP
iptables -A FORWARD		-j DROP
iptables -A DOCKER-USER -j DROP

# Verificando se é para salvar as regras
if [[ $1 == "--salvar" ]]; then
	iptables-save 		> /etc/iptables/rules.v4
	iptables-restore 	< /etc/iptables/rules.v4

	ip6tables-save		> /etc/iptables/rules.v6
	ip6tables-restore	< /etc/iptables/rules.v6
fi

if [[ $1 == "--limpar" ]]; then
	iptables 	-F
	iptables 	-X
	iptables 	-t nat -F
	ip6tables	-F
fi
