#!/bin/bash
# Arquivo com as regras IPTABLES do meu VPS particular
# Criado por Rafael Arcanjo
#
# Argumentos
#	--limpar Limpa todas as regras do firewall
#	--salvar Aplica as regras e salva no iptables-persistent

input="iptables -A INPUT"
output="iptables -A OUTPUT"
forward="iptables -A FORWARD"
prerouting="iptables -t nat -A PREROUTING"
postrouting="iptables -t nat -A POSTROUTING"
ip="51.222.16.143"
docker="172.17.0.1/16"
vpn="10.8.0.1/24"
path="/root/bin/firewallArquivos"
ipsBlock="$path/ipsBlock"
ipsConfiaveis="$path/ipsConfiaveis"

# Limpando
iptables -F
iptables -X
iptables -t nat -F
iptables -t nat -X

# Loopback
$input	-i lo -s 127.0.0.1 -j ACCEPT
$output -o lo -d 127.0.0.1 -j ACCEPT

# Bloqueando IPs
if [[ -f $ipsBlock ]]; then
	for x in $(cat $ipsBlock | uniq | sort -n); do
		$input		-s $x -j DROP
		$output		-d $x -j DROP
		$forward	-s $x -j DROP
		$forward	-d $x -j DROP
	done
fi

# Reiniciando o DOCKER
service docker restart

# Liberando o MASQUERADE
$postrouting -j MASQUERADE

# Pacotes estabelecidos e relacionados
$input	-m state --state ESTABLISHED,RELATED -j ACCEPT
$output	-m state --state ESTABLISHED,RELATED -j ACCEPT

# PING
$input	-p icmp --icmp-type echo-request -m limit --limit 1/s -j ACCEPT
$output	-p icmp --icmp-type echo-request -m limit --limit 1/s -j ACCEPT

# SSH
$input -p tcp --dport 22922 -d $ip -j ACCEPT

# Navegação
$output	-p tcp --dport 80	-j ACCEPT
$output	-p tcp --dport 443	-j ACCEPT

# DNS
$output -p udp --dport 53 -j ACCEPT

# Descarta pacotes reincidentes/persistentes
$input		-m recent --update --name SUSPEITO -m limit --limit 10/min --limit-burst 3 -j LOG --log-level 6 --log-prefix "FIREWALL: suspeito: "
$input 		-m recent --update --hitcount 10 --name SUSPEITO --seconds 86400 -j DROP
$input		-m recent --update --hitcount 5  --name SUSPEITO --seconds 3600  -j DROP
$forward	-m recent --update --hitcount 10 --name SUSPEITO --seconds 86400 -j DROP
$forward	-m recent --update --hitcount 5  --name SUSPEITO --seconds 3600  -j DROP

# Liberando VPN
$input -p udp --dport 53532 -j ACCEPT

# Liberando o VPN conectar no DOCKER
$forward -i tun0 -o docker0 -j ACCEPT

# Liberando o NGINX para o HASS
$input -p tcp --dport 44333 -j ACCEPT

# Liberando o transmission
$prerouting -p tcp --dport 9091 -j DNAT --to-destination 10.8.0.2:9091
$forward -d 10.8.0.2 -p tcp --dport 9091 -j ACCEPT
$forward -s 10.8.0.2 -p tcp --sport 9091 -j ACCEPT

# Descarta pacotes inválidos
$input		-m state --state INVALID -j DROP
$forward	-m state --state INVALID -j DROP

#*********************************#
# Não colocar regras abaixo daqui #
#*********************************#
# Dropgando tudo que é ipv6
ip6tables -A INPUT		-j DROP
ip6tables -A OUTPUT		-j DROP
ip6tables -A FORWARD	-j DROP

# Logando o que restou
$input		-j LOG --log-level 6 --log-prefix "FIREWALL: drop input: "
$output		-j LOG --log-level 6 --log-prefix "FIREWALL: drop output: "
$forward	-j LOG --log-level 6 --log-prefix "FIREWALL: drop forward: "

# Droptando o restante
$input		-j DROP
$output		-j DROP

# Verificando se é para salvar as regras
if [[ $1 == "--salvar" ]]; then
	iptables-save 		> /etc/iptables/rules.v4
	iptables-restore 	< /etc/iptables/rules.v4

	ip6tables-save		> /etc/iptables/rules.v6
	ip6tables-restore	< /etc/iptables/rules.v6
fi

if [[ $1 == "--limpar" ]]; then
	iptables 	-F
	iptables 	-X
	iptables 	-t nat -F
	ip6tables	-F
fi
